apps/contacts/urls.py
from django.urls import path
from .views import *

app_name = 'contacts'

urlpatterns = [
    path('', ContactCreateView.as_view(), name = 'contactus'),
    path('success/', ThanksView.as_view(), name = 'thanks'),
]

apps/gallery/urls.py
from django.urls import path
from . import views

app_name = 'gallery'

urlpatterns = [
    path('', views.GalleryView.as_view(), name = 'index'),
]

apps/posts/urls.py
from django.urls import path
from .views import *


app_name = 'posts'

urlpatterns = [
    # Posts
    path('', PostListView.as_view(), name='index'),
    path('v/<slug:slug>', PostDetailView.as_view(), name='view'),
    path('create/', PostCreateView.as_view(), name='create'),
    path('<slug:slug>/delete', PostDeleteView.as_view(), name='delete'),
    path('<slug:slug>/update', PostUpdateView.as_view(), name='update'),
    path('<slug:slug>/like', like_post, name='like'),

    # Comments
    path('<slug:slug>/comment', PostCommentCreateView.as_view(), name='add_comment'),
    path('<slug:slug>/comment/<uuid:cpk>/delete',
         PostCommentDeleteView.as_view(), name='delete_comment'),
    path('<slug:slug>/comment/<uuid:cpk>/update',
         PostCommentUpdateView.as_view(), name='update_comment'),

    # Categories
    path('category/create', PostCategoryCreateView.as_view(), name='create_category'),
    path('category/<slug:slug>/update',
         PostCategoryUpdateView.as_view(), name='update_category'),
    path('category/<slug:slug>/delete',
         PostCategoryDeleteView.as_view(), name='delete_category'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.error_handling.views import *

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('apps.sections.urls')),
    path('posts/', include('apps.posts.urls')),
    path('', include('apps.users.urls')),
    path('contacts/', include('apps.contacts.urls')),
    path('gallery/', include('apps.gallery.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = custom_access_denied
handler404 = custom_page_not_found

apps/contacts/models.py
from django.db import models
from django.urls import reverse

class Contact(models.Model):
    name = models.CharField(max_length=50, verbose_name='Nombre')
    email = models.EmailField(verbose_name='Correo electrónico')
    subject = models.CharField(max_length=150, verbose_name='Asunto')
    message = models.TextField(max_length=500, verbose_name='Mensaje')
    created_at = models.DateTimeField(auto_now = True, editable=False, verbose_name='Fecha de creación')
    readed = models.BooleanField(default=False, verbose_name='Fue leído?')
    
    class Meta:
        verbose_name = 'Contacto'
        verbose_name_plural = 'Contactos'
    
    def __str__(self):
        return self.email
    
    def get_absolute_url(self):
        return reverse("gallery:index")
    

apps/gallery/models.py
from django.db import models

class GalleryImage(models.Model):
    image = models.ImageField(upload_to='gallery_images')
    caption = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.caption

apps/contacts/forms.py
from django import forms
from .models import *

class ContactForm(forms.ModelForm):
    
    class Meta:
        model = Contact
        exclude = ['created_at', 'readed']

apps/contacts/views.py
from django.views.generic import CreateView, TemplateView
from .models import *
from .forms import *
from django.urls import reverse_lazy


class ContactCreateView(CreateView):
    model = Contact
    template_name = 'contacts/create.html'
    form_class = ContactForm
    success_url = reverse_lazy('contacts:thanks')
    
class ThanksView(TemplateView):
    template_name = 'contacts/thanks.html'

apps/gallery/views.py
from django.views.generic import ListView
from .models import GalleryImage

class GalleryView(ListView):
    model = GalleryImage
    template_name = 'gallery/gallery.html'
    context_object_name = 'images'

templates/includes/about.html
{% load static %}
<section class="bg-dark text-light ">
    <section class="container py-5">
      <div class="row text-center py-3">
        <div class="col-lg-6 m-auto">
          <h1 class="h1">Quienes somos</h1>
          <p>Quienes conformamos la ONG El Hornero somos los siguientes:</p>
        </div>
      </div>
      <div class="row">
        <div class="col-12 col-md-6 mb-4">
            <div class="card h-100">
              <div class="card-body">
                <img src="{% static 'img/hornero_icon.png' %}" alt="" class="img-fluid h-100 object-fit-cover" />
              </div>
            </div>
          </div>
        <div class="col-12 col-md-6 mb-4 ">
            <ul class="d-flex flex-column flex-wrap justify-content-evenly h-100">
                <li><b>Monzón Marisa</b> - <b class="text-muted">Presidente</b></li>
                <li><b>Hugo Folch</b> - <b class="text-muted">Vice-presidente</b></li>
                <li><b>Belén Folch</b> - <b class="text-muted">Secretaria</b></li>
                <li><b>Luis Otazo</b> - <b class="text-muted">Tesorero</b></li>
                <li><b>Ignacio Ozorio</b> - <b class="text-muted">1° Vocal Titular</b></li>
                <li><b>Hugo Baldore</b> - <b class="text-muted">2° Vocal Titular</b></li>
                <li><b>Fortín Javier</b> - <b class="text-muted">3° Vocal Titular</b></li>
                <li><b>Rivero Alicia</b> - <b class="text-muted">1° Vocal Suplente</b></li>
                <li><b>Neri Otazo</b> - <b class="text-muted">2° Vocal Suplente</b></li>
                <li><b>Caputo Priscila</b> - <b class="text-muted">3° Vocal Suplente</b></li>
                <li><b>Renedo Alcides</b> - <b class="text-muted">Revisor de Cuentas</b></li>
                <li><b>Ruiz Díaz Daniel</b> - <b class="text-muted">Revisor de Cuentas Suplente</b></li>
            </ul>            
        </div>
      </div>
    </section>
  </section>
  <section class="bg-secondary text-center">
    <a href="#index-contact" class="btn text-white py-4 align-middle"><h4><b>Contactanos <i class="bi bi-arrow-right"></i></b></h4></a>
  </section>

templates/includes/carousel.html
{% load static %}
<section class="">
    <div id="hero-carousel" class="carousel slide">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#hero-carousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#hero-carousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#hero-carousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
      </div>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="{% static 'img/ONG/IMG-20231004-WA0030.jpg' %}" class="carousel-img d-block w-100 object-fit-cover" alt="..." />
          <div class="carousel-caption d-none d-md-block">
            <h5></h5>
            <p></p>
          </div>
        </div>
        <div class="carousel-item">
          <img src="{% static 'img/ONG/IMG-20231004-WA0038.jpg' %}" class="carousel-img d-block w-100 object-fit-cover" alt="..." />
          <div class="carousel-caption d-none d-md-block">
            <h5></h5>
            <p></p>
          </div>
        </div>
        <div class="carousel-item">
          <img src="{% static 'img/ONG/IMG-20231004-WA0039.jpg' %}" class="carousel-img d-block w-100 object-fit-cover" alt="..." />
          <div class="carousel-caption d-none d-md-block">
            <h5></h5>
            <p></p>
          </div>
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#hero-carousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#hero-carousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </section>

templates/includes/contact.html
{% load static %}
<section id="index-contact">
  <div class="container py-5">
    <div class="row text-center ">
      <h1>Déjanos un mensaje</h1>
    </div>
    <div class="row py-5">
      <form class="col-md-9 m-auto" method="post" role="form" id="form-contacto" action="{% url 'contacts:contactus' %}">
        {% csrf_token %}
        <div class="row">
          <div class="form-group col-md-6 mb-3">
            <label for="inputname">Nombre</label>
            <input type="text" class="form-control mt-1" id="id_name" name="name" placeholder="Nombre" required="" />
          </div>
          <div class="form-group col-md-6 mb-3">
            <label for="inputemail">Correo electrónico</label>
            <input type="email" class="form-control mt-1" id="id_email" name="email" placeholder="Correo electrónico" required="" />
          </div>
        </div>
        <div class="mb-3">
          <label for="inputsubject">Asunto</label>
          <input type="text" class="form-control mt-1" id="id_subject" name="subject" placeholder="Asunto" required="" />
        </div>
        <div class="mb-3">
          <label for="inputmessage">Mensaje</label>
          <textarea class="form-control mt-1" id="id_message" name="message" placeholder="Mensaje" rows="8" required=""></textarea>
        </div>
        <div class="row">
          <div class="col text-end mt-2">
            <button type="submit" class="btn btn-success btn-lg px-3">Hablemos</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</section>

templates/includes/featured_posts.html
{% load static %}
<section class="bg-light">
  <section class="container py-5">
    <div class="row text-center py-3">
      <div class="col-lg-6 m-auto">
        <h1 class="h1">Art&iacute;culos destacados</h1>
        <p>Aqu&iacute; puedes ver los art&iacute;culos m&aacute;s destacados</p>
      </div>
    </div>
    <div class="row">
      {% for post in featured_posts %}
        <div class="col-12 col-md-4 mb-4">
          <div class="card h-100">
            <div class="card-body">
              <a href="{{ post.get_absolute_url }}" class="text-black text-decoration-none ">
                <img src="{{ post.image.url }}" alt="" class="post-thumbnail-image" />
                <h2>{{ post.title }}</h2>
                <p>{{ post.short_description }}</p>
              </a>
            </div>
          </div>
        </div>
        {% empty %}
      {% endfor %}
    </div>
  </section>
</section>
<div class="bg-info text-center">
  <a href="{% url 'posts:index' %}" class="btn text-white py-4 align-middle"><h4><b>Ver más art&iacute;culos</b><i class="bi bi-arrow-right"></i></h4></a>
</div>

templates/includes/footer.html
<footer class="footer mt-auto py-3 bg-dark ">
  <div class="container">
    <span class="text-muted">Desarrollado por <a class="text-decoration-none" href="https://github.com/montexbjeliseo" target="_blank">@montexbjeliseo</a> 2023</span>
  </div>
</footer>

templates/includes/gallery.html
{% load static %}
<section class="bg-light">
    <section class="container py-5">
      <div class="row text-center py-3">
        <div class="col-lg-6 m-auto">
          <h1 class="h1">Galería</h1>
          <p>Aquí puedes ver las imágenes destacadas</p>
        </div>
      </div>
      <div class="row">
        <div class="col-12 col-md-4 mb-4">
          <div class="card h-100">
            <div class="card-body">
              <img src="{% static 'img/ONG/IMG-20231004-WA0030.jpg' %}" alt="" class="gallery-image" />
            </div>
          </div>
        </div>
        <div class="col-12 col-md-4 mb-4">
          <div class="card h-100">
            <div class="card-body">
              <img src="{% static 'img/ONG/IMG-20231004-WA0038.jpg' %}" alt="" class="gallery-image" />
            </div>
          </div>
        </div>
        <div class="col-12 col-md-4 mb-4">
          <div class="card h-100">
            <div class="card-body">
              <img src="{% static 'img/ONG/IMG-20231004-WA0039.jpg' %}" alt="" class="gallery-image" />
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-12 col-md-4 mb-4">
          <div class="card h-100">
            <div class="card-body">
              <img src="{% static 'img/ONG/IMG-20231004-WA0036.jpg' %}" alt="" class="gallery-image" />
            </div>
          </div>
        </div>
        <div class="col-12 col-md-4 mb-4">
          <div class="card h-100">
            <div class="card-body">
              <img src="{% static 'img/ONG/IMG-20231004-WA0042.jpg' %}" alt="" class="gallery-image" />
            </div>
          </div>
        </div>
        <div class="col-12 col-md-4 mb-4">
          <div class="card h-100">
            <div class="card-body">
              <img src="{% static 'img/ONG/IMG-20231004-WA0041.jpg' %}" alt="" class="gallery-image" />
            </div>
          </div>
        </div>
      </div>
    </section>
  </section>
  <section class="bg-primary text-center">
    <a href="{% url 'gallery:index' %}" class="btn text-white py-4 align-middle"><h4><b>Ver más imágenes <i class="bi bi-arrow-right"></i></b></h4></a>
  </section>

  <script src="{% static 'js/gallery.js' %}"></script>

templates/includes/header.html
{% load path_tags %}
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'index' %}">{{ app_name }}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Inicio</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about' %}">Nosotros</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Categorías</a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for category in categories %}
                <li>
                  <a class="dropdown-item" href="{{ category.get_filterby_link }}">{{ category }}</a>
                </li>
              {% endfor %}
              <li>
                <hr class="dropdown-divider" />
              </li>
              <li>
                <a class="dropdown-item" href="{% url 'posts:index' %}">Todos los articulos</a>
              </li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Ingresar</a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% if user.is_authenticated %}
                {% if user.is_staff %}
                  <li>
                    <a href="{% url 'admin:index' %}" class="dropdown-item">Administración</a>
                  </li>
                  <li>
                    <a href="{% url 'list_sections' %}" class="dropdown-item">Personalización</a>
                  </li>
                {% endif %}
                <li>
                  <a href="{{user.get_absolute_url}}" class="dropdown-item">Mi Perfil</a>
                </li>
                <li>
                  <hr class="dropdown-divider" />
                </li>
                <li>
                  <a href="{% confirm_logout_path %}" class="dropdown-item">Cerrar sesión</a>
                </li>
              {% else %}
                <li>
                  <a href="{% login_path %}" class="dropdown-item">Iniciar sesión</a>
                </li>
                <li>
                  <a href="{% register_path %}" class="dropdown-item">Registrarse</a>
                </li>
              {% endif %}
            </ul>
          </li>
        </ul>
        {% include 'includes/search.html' %}
      </div>
    </div>
  </nav>
  {% include 'includes/messages.html' %}
</header>

templates/includes/messages.html
<div>
    {% for message in messages %}
    <div class="alert{% if message.tags %} alert-{{ message.tags }}{% endif %} alert-dismissible fade show"
        role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
</div>

templates/includes/search.html
<form class="d-flex" method="GET" action="{% url 'posts:index' %}">
    <input name="q" class="form-control me-2" type="search" placeholder="Buscar" aria-label="Search" value="{{request.GET.q}}">
    <button class="btn btn-outline-success" type="submit">Buscar</button>
</form>